# default configuration
baseURL = "https://www-hugo.remoteteam.workers.dev/"
languageCode = "en-us"
summaryLength = "10"
theme = "remoteteam"
title = "Remote Team | Remote Team is an HR platform for “Remote First” teams. Our fully-integrated platform automates payroll, payments and HR tasks."
description = "Remote Team is an HR platform for “Remote First” teams. Our fully-integrated platform automates payroll, payments and HR tasks."

enableRobotsTXT = true

[taxonomies]
  tag = "blog/tags"
  category = "categories"
  

# support html in markdown
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# menu

[[menu.main]]
URL = "payroll"
name = "Payroll"
parent = "Platform"
weight = 2

[[menu.main]]
URL = "time-off"
name = "Time Off"
parent = "Platform"
weight = 2

[[menu.main]]
URL = "pricing"
name = "Pricing"
weight = 3


[[menu.main]]
URL = "resources"
name = "Posts"
parent = "Resources"
weight = 5

[[menu.main]]
URL = "virtual-zoom-backgrounds"
name = "Zoom Backgrounds"
parent = "Resources"
weight = 5

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 5



disableHugoGeneratorInject = true
publishDir = "dist"

# default parameters
[params]
home = "Home"
logo = "https://res.cloudinary.com/hebu10lmu/image/upload/q_auto,c_scale,w_119/v1579546392/www/logo-light_mijgnj.png"
# theme color
theme_color = "#2d46c1"
# contact info
phone = "+880 2544 658 256"
email = "support@remoteteam.com"
address = "156 2nd Street San Francisco, CA 94105"
# meta description
author = "Remote Team"
description = "This is meta description"
# google analytics
google_analytics_id = "UA-114129024-1"
# copyright
copyright = "Copyright &copy; 2020"


# social site
[[params.social]]
URL = "https://twitter.com/remoteteamcom"
TITLE = "Twitter"

[[params.social]]
URL = "https://www.linkedin.com/company/remoteteam"
TITLE = "Linkedin"

[[params.social]]
URL = "https://stackshare.io/companies/remoteteam"
TITLE = "StackShare"

[mediaTypes]
  [mediaTypes."image/svg+xml"]
    suffixes = ["svg"]
