name = "RemoteTeam"
license = "MIT"
licenselink = "https://github.com/remoteteam/www"
description = "RemoteTeam Template"
homepage = "https://remoteteam.com"
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages', 'resume', 'portfolio', 'google analytics', 'customizable', 'flexbox', 'presentation', 'product', 'theme', 'typography']
features = ['bootstrap','responsive']
min_version = "0.64.0"

[author]
  name = "RemoteTeam"
  homepage = "https://remoteteam.com"

[original]
  name = "remoteteam"
  homepage = "https://remoteteam.com"